server/casting/config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :auditions
  resources :actors_projects
  resources :projects
  resources :actors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/casting/app/models/audition.rb
class Audition < ApplicationRecord
end

server/casting/app/controllers/auditions_controller.rb
class AuditionsController < ApplicationController
  before_action :set_audition, only: [:show, :edit, :update, :destroy]

  # GET /auditions
  # GET /auditions.json
  def index
    @auditions = Audition.all
  end

  # GET /auditions/1
  # GET /auditions/1.json
  def show
  end

  # GET /auditions/new
  def new
    @audition = Audition.new
  end

  # GET /auditions/1/edit
  def edit
  end

  # POST /auditions
  # POST /auditions.json
  def create
    @audition = Audition.new(audition_params)

    respond_to do |format|
      if @audition.save
        format.html { redirect_to @audition, notice: 'Audition was successfully created.' }
        format.json { render :show, status: :created, location: @audition }
      else
        format.html { render :new }
        format.json { render json: @audition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auditions/1
  # PATCH/PUT /auditions/1.json
  def update
    respond_to do |format|
      if @audition.update(audition_params)
        format.html { redirect_to @audition, notice: 'Audition was successfully updated.' }
        format.json { render :show, status: :ok, location: @audition }
      else
        format.html { render :edit }
        format.json { render json: @audition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auditions/1
  # DELETE /auditions/1.json
  def destroy
    @audition.destroy
    respond_to do |format|
      format.html { redirect_to auditions_url, notice: 'Audition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audition
      @audition = Audition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audition_params
      params.fetch(:audition, {})
    end
end

server/casting/app/helpers/auditions_helper.rb
module AuditionsHelper
end

server/casting/app/views/auditions/_form.html.erb
<%= form_with(model: audition, local: true) do |form| %>
  <% if audition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(audition.errors.count, "error") %> prohibited this audition from being saved:</h2>

      <ul>
      <% audition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

server/casting/app/views/auditions/edit.html.erb
<h1>Editing Audition</h1>

<%= render 'form', audition: @audition %>

<%= link_to 'Show', @audition %> |
<%= link_to 'Back', auditions_path %>

server/casting/app/views/auditions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auditions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auditions.each do |audition| %>
      <tr>
        <td><%= link_to 'Show', audition %></td>
        <td><%= link_to 'Edit', edit_audition_path(audition) %></td>
        <td><%= link_to 'Destroy', audition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Audition', new_audition_path %>

server/casting/app/views/auditions/new.html.erb
<h1>New Audition</h1>

<%= render 'form', audition: @audition %>

<%= link_to 'Back', auditions_path %>

server/casting/app/views/auditions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_audition_path(@audition) %> |
<%= link_to 'Back', auditions_path %>