server/casting/config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :auditions
  resources :actors_projects
  resources :projects
  resources :actors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/casting/app/models/actors_project.rb
class ActorsProject < ApplicationRecord
end

server/casting/app/controllers/actors_projects_controller.rb
class ActorsProjectsController < ApplicationController
  before_action :set_actors_project, only: [:show, :edit, :update, :destroy]

  # GET /actors_projects
  # GET /actors_projects.json
  def index
    @actors_projects = ActorsProject.all
  end

  # GET /actors_projects/1
  # GET /actors_projects/1.json
  def show
  end

  # GET /actors_projects/new
  def new
    @actors_project = ActorsProject.new
  end

  # GET /actors_projects/1/edit
  def edit
  end

  # POST /actors_projects
  # POST /actors_projects.json
  def create
    @actors_project = ActorsProject.new(actors_project_params)

    respond_to do |format|
      if @actors_project.save
        format.html { redirect_to @actors_project, notice: 'Actors project was successfully created.' }
        format.json { render :show, status: :created, location: @actors_project }
      else
        format.html { render :new }
        format.json { render json: @actors_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors_projects/1
  # PATCH/PUT /actors_projects/1.json
  def update
    respond_to do |format|
      if @actors_project.update(actors_project_params)
        format.html { redirect_to @actors_project, notice: 'Actors project was successfully updated.' }
        format.json { render :show, status: :ok, location: @actors_project }
      else
        format.html { render :edit }
        format.json { render json: @actors_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors_projects/1
  # DELETE /actors_projects/1.json
  def destroy
    @actors_project.destroy
    respond_to do |format|
      format.html { redirect_to actors_projects_url, notice: 'Actors project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actors_project
      @actors_project = ActorsProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actors_project_params
      params.fetch(:actors_project, {})
    end
end

server/casting/app/helpers/actors_projects_helper.rb
module ActorsProjectsHelper
end

server/casting/app/views/actors_projects/_form.html.erb
<%= form_with(model: actors_project, local: true) do |form| %>
  <% if actors_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actors_project.errors.count, "error") %> prohibited this actors_project from being saved:</h2>

      <ul>
      <% actors_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

server/casting/app/views/actors_projects/edit.html.erb
<h1>Editing Actors Project</h1>

<%= render 'form', actors_project: @actors_project %>

<%= link_to 'Show', @actors_project %> |
<%= link_to 'Back', actors_projects_path %>

server/casting/app/views/actors_projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors Projects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors_projects.each do |actors_project| %>
      <tr>
        <td><%= link_to 'Show', actors_project %></td>
        <td><%= link_to 'Edit', edit_actors_project_path(actors_project) %></td>
        <td><%= link_to 'Destroy', actors_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actors Project', new_actors_project_path %>

server/casting/app/views/actors_projects/new.html.erb
<h1>New Actors Project</h1>

<%= render 'form', actors_project: @actors_project %>

<%= link_to 'Back', actors_projects_path %>

server/casting/app/views/actors_projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_actors_project_path(@actors_project) %> |
<%= link_to 'Back', actors_projects_path %>